### ISSUE TITLE
不兼容 BewlyBewly 的顶栏

### ISSUE THREAD

**Issue by SettingDust** [posthumz/wider-bilibili#1]
https://github.com/BewlyBewly/BewlyBewly/issues/427

**Comment by posthumz** [comment]
之前适配过，然后BewlyBewly把整个`#biliMainHeader`隐藏了导致现在不显示了。改完应该没问题了

**Comment by SettingDust** [comment]
会导致覆盖 
![图片](https://github.com/user-attachments/assets/2183a911-42bc-4517-8be8-20f7b0bf81c0)

**Comment by posthumz** [comment]
> 会导致覆盖 ![图片](https://private-user-images.githubusercontent.com/19922286/380477940-2183a911-42bc-4517-8be8-20f7b0bf81c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMTgzMDgsIm5iZiI6MTczMDAxODAwOCwicGF0aCI6Ii8xOTkyMjI4Ni8zODA0Nzc5NDAtMjE4M2E5MTEtNDJiYy00NTE3LThiZTgtMjBmN2IwYmY4MWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA4MzMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMzdkY2I5ODdmYmUxOWYxMDIxNDU2MDVlNjQxMWEwNjZiZWQ4ODNkMzdmNjM2YzlhMmM2YWQxNzIyMjhlMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XrNsEMCEE36aSOV1nBmqwdYOdvPkU4vnL8wn91oO6Go)

复现不了，浏览器环境是什么

**Comment by SettingDust** [comment]
floorp（firefox），向下滚动，bewly 会隐藏顶栏，translate -100%，所以就这样了

**Comment by posthumz** [comment]
> floorp（firefox），向下滚动，bewly 会隐藏顶栏，translate -100%，所以就这样了

那把`自动隐藏顶栏`关了？

**Comment by SettingDust** [comment]
![图片](https://github.com/user-attachments/assets/4a9a683e-21f4-4bf2-9104-17a0773cafd0)

字全都变黑了，好像是路径变了导致某个 css 没应用到或者优先级乱了，没有本插件是正常的.0.

**Comment by posthumz** [comment]
我不知道怎么不用改变元素路径的方法适配我这个脚本的实现，如果有想法欢迎pr
不过我还是建议直接在BewlyBewly里面选择`使用原版 Bilibili 顶栏`
